import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';

mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  themeVariables: {
    primaryColor: '#1e2d4a', primaryTextColor: '#f1f5f9',
    primaryBorderColor: '#6366f1', lineColor: '#475569',
    secondaryColor: '#161f38', tertiaryColor: '#0f1629',
    edgeLabelBackground: '#0f1629', titleColor: '#818cf8',
  },
  flowchart: { curve: 'basis', padding: 20 },
  securityLevel: 'loose',
});

let seq = 0;

function Skeleton() {
  const rows = [[240, 180], [180, 220], [200]];
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20, alignItems: 'center', padding: 24 }}>
      {rows.map((cols, i) => (
        <div key={i} style={{ display: 'flex', gap: 32, alignItems: 'center' }}>
          {cols.map((w, j) => (
            <React.Fragment key={j}>
              <div className="skeleton" style={{ width: w, height: 44, borderRadius: 10 }} />
              {j < cols.length - 1 && <div className="skeleton" style={{ width: 48, height: 2 }} />}
            </React.Fragment>
          ))}
        </div>
      ))}
    </div>
  );
}

export default function DiagramTab({ diagram, isAnalyzing }) {
  const ref        = useRef(null);
  const [scale, setScale]       = useState(1);
  const [hasError, setHasError] = useState(false);
  const [ready, setReady]       = useState(false);

  // Render is intentionally not memoised — it's only called from the effect
  // below, and a closure over `diagram` would otherwise re-create the callback
  // every render anyway. Define it inline inside the effect to keep deps clean.
  useEffect(() => {
    if (!diagram || !ref.current) return;
    let cancelled = false;

    (async () => {
      setHasError(false);
      setReady(false);
      try {
        const id = `gm-d-${++seq}`;
        const { svg } = await mermaid.render(id, diagram);
        if (cancelled || !ref.current) return;
        ref.current.innerHTML = svg;
        const svgEl = ref.current.querySelector('svg');
        if (svgEl) { svgEl.style.maxWidth = '100%'; svgEl.style.height = 'auto'; }
        setReady(true);
      } catch (err) {
        if (cancelled) return;
        console.error('[DiagramTab] Mermaid parse error:', err);
        setHasError(true);
        if (ref.current) {
          // Escape so a malformed diagram can't inject HTML
          const escaped = diagram.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
          ref.current.innerHTML = `<pre style="color:#94a3b8;font-size:11px;padding:16px;white-space:pre-wrap;font-family:'JetBrains Mono',monospace;line-height:1.6">${escaped}</pre>`;
        }
        setReady(true);
      }
    })();

    return () => { cancelled = true; };
  }, [diagram]);

  const btnStyle = {
    width: 30, height: 30, borderRadius: 7, background: 'var(--gm-surface-2)',
    border: '1px solid var(--gm-border)', color: 'var(--gm-text-2)', cursor: 'pointer',
    fontSize: 14, display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.15s',
  };

  if (!diagram && !isAnalyzing) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '60vh', gap: 16 }}>
        <div style={{ width: 72, height: 72, borderRadius: 18, background: 'var(--gm-surface)', border: '2px dashed var(--gm-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 30 }}>🏗</div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--gm-text-2)', marginBottom: 6 }}>No diagram yet</div>
          <div style={{ fontSize: 13, color: 'var(--gm-text-3)' }}>Analyze a repository to auto-generate the architecture</div>
        </div>
      </div>
    );
  }

  if (isAnalyzing && !diagram) {
    return (
      <div>
        <div style={{ fontSize: 13, color: 'var(--gm-primary)', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ animation: 'gm-glow-pulse 1.5s ease-in-out infinite', display: 'inline-block' }}>🏗</span>
          Architecture Agent is mapping the codebase…
        </div>
        <div style={{ background: 'var(--gm-surface)', border: '1px solid var(--gm-border)', borderRadius: 14 }}><Skeleton /></div>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', gap: 12 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0 }}>
        <div style={{ fontSize: 12, color: 'var(--gm-text-3)', display: 'flex', alignItems: 'center', gap: 6 }}>
          <span>🏗 Auto-generated by Architecture Agent</span>
          {hasError && <span style={{ color: 'var(--gm-warning)' }}>· Parse error — showing raw Mermaid</span>}
        </div>
        {ready && !hasError && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
            <button style={btnStyle} onClick={() => setScale(s => Math.max(s - 0.15, 0.3))} title="Zoom out">−</button>
            <span style={{ fontSize: 11, color: 'var(--gm-text-3)', width: 38, textAlign: 'center', fontFamily: 'JetBrains Mono,monospace' }}>{Math.round(scale * 100)}%</span>
            <button style={btnStyle} onClick={() => setScale(s => Math.min(s + 0.15, 3))} title="Zoom in">+</button>
            <button style={{ ...btnStyle, width: 'auto', padding: '0 10px', fontSize: 11 }} onClick={() => setScale(1)}>⊡ Fit</button>
          </div>
        )}
      </div>
      {/* Outer scroll container */}
      <div style={{ flex: 1, overflow: 'auto', background: 'var(--gm-surface)', border: '1px solid var(--gm-border)', borderRadius: 14, boxShadow: 'inset 0 0 40px rgba(0,0,0,0.2)' }}>
        {/* Inner wrapper grows to fit scaled content so scroll works */}
        <div style={{ display: 'inline-block', minWidth: '100%', padding: 24, boxSizing: 'border-box' }}>
          <div
            ref={ref}
            className="diagram-canvas fade-up"
            style={{
              transformOrigin: 'top left',
              transform: `scale(${scale})`,
              transition: 'transform 0.2s ease',
              /* push the scroll container to match real scaled size */
              width:  `${Math.round(100 / scale)}%`,
              height: scale !== 1 ? `${Math.round(100 / scale)}%` : 'auto',
            }}
          />
        </div>
      </div>
    </div>
  );
}
